### ISSUE TITLE
Tests failing with 1.6, 1.5

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#100]
Tests are failing with both Clojure 1.6 and 1.5. 

```
Performing task 'expectations' with profile(s): 'base,system,user,provided,dev,1.5'
Exception in thread "main" java.io.FileNotFoundException: Could not locate expectations__init.class or expectations.clj on classpath:
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5413)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$require.doInvoke(core.clj:5496)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval9.invoke(form-init6240070169091355564.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Error encountered performing task 'expectations' with profile(s): 'base,system,user,provided,dev,1.5'
Subprocess failed
```

Can't find any documentation on expectations to see if they are still supported.  Any reason to support them moving forward?

**Comment by ptaoussanis** [comment]
Hi Ricardo,

Have reverted to an earlier version of Expectations that I believe has support for Clojure 1.5 (unconfirmed, going by memory). TBH would be keen to switch away from Expectations (to clojure.test) for a variety of reasons, but don't think it's urgent.

In any event, I believe that very few users are currently still stuck on Clojure 1.5. Would be okay for Faraday v1.10.0 to officially break support if a compelling reason presents.

**Comment by ricardojmendez** [comment]
Acknowledged, closing the issue for now.
